# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/exasol/serial-version-uid-change-pre-commit-hook
    rev: master
    hooks:
      - id: serial-version-uid
        language_version: python3.7
