sources:
  - type: maven
    path: pom.xml
    modules:
      - integration_tests
      - jar_artifact
      - udf_coverage
  - type: npm
    path: extension/package.json
version:
  fromSource: pom.xml
linkReplacements:
  - https://netty.io/netty-codec/|https://netty.io/
excludes:
  - "E-PK-CORE-18: Outdated content: '.github/workflows/ci-build.yml'"
  - "E-PK-CORE-18: Outdated content: '.github/workflows/release_droid_prepare_original_checksum.yml'"
  - "E-PK-CORE-18: Outdated content: '.github/workflows/release_droid_upload_github_release_assets.yml'"
  - regex: "(?s)E-PK-CORE-53: The dependencies.md file has outdated content.*"
