name: CI Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build with Exasol ${{ matrix.exasol_db_version }}
    runs-on: ubuntu-20.04 # UDFs fail with "VM error: Internal error: VM crashed" on ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        exasol_db_version: ["7.1.24", "8.23.1"]
    env:
      DEFAULT_EXASOL_DB_VERSION: "7.1.24"
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.exasol_db_version }}
      cancel-in-progress: true
    steps:
      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 11 & 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: |
            17
            11
          cache: "maven"
      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: extension/package-lock.json
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Enable testcontainer reuse
        run: echo 'testcontainers.reuse.enable=true' > "$HOME/.testcontainers.properties"
      - name: Create test_config.properties
        run: |
          echo "owner = ${{ secrets.AWS_TAG_OWNER }}" > test_config.properties
          echo "s3CacheBucket = persistent-s3-vs-test-file-cache" >> test_config.properties
      - name: Run tests and build with Maven
        run: |
          JAVA_HOME=$JAVA_HOME_11_X64 mvn --batch-mode clean verify \
              -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
              -DtrimStackTrace=false \
              -Dcom.exasol.dockerdb.image=${{ matrix.exasol_db_version }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-central-1"
      - name: Upload generated class list to artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: generated-classes.lst
          path: target/generated-classes.lst
      - name: Publish Test Report
        uses: scacap/action-surefire-report@v1
        if: ${{ always() && github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Sonar analysis
        if: ${{ env.SONAR_TOKEN != null && matrix.exasol_db_version == env.DEFAULT_EXASOL_DB_VERSION }}
        run: |
          JAVA_HOME=$JAVA_HOME_17_X64 mvn --batch-mode org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
              -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
              -DtrimStackTrace=false \
              -Dsonar.organization=exasol \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.token=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
