name: CI Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'maven'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: extension/package-lock.json
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Create test_config.yml
        run: |
          echo "owner: ${{ secrets.AWS_TAG_OWNER }}" > test_config.yml
          echo "s3CacheBucket: persistent-s3-vs-test-file-cache" >> test_config.yml
      - name: Run tests and build with Maven
        run: mvn --batch-mode --update-snapshots clean verify -DtrimStackTrace=false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-central-1"

      - name: Build extension
        run: |
          cd extension
          npm ci
          npm run build

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Upload generated class list to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: generated-classes.lst
          path: target/generated-classes.lst
        if: always()