name: Regression Tests

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print tag name
        run: echo ${{ github.event.release.tag_name }}
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Create AWS test setup
        run: |
          echo "owner = \"$OWNER\"" > cloudSetup/terraform.tfvars
          echo "deputy = \"$DEPUTY\"" >> cloudSetup/terraform.tfvars
          terraform -chdir=cloudSetup/ init
          terraform -chdir=cloudSetup/ apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          OWNER: ${{ secrets.AWS_TAG_OWNER }}
          DEPUTY: ${{ secrets.AWS_TAG_DEPUTY }}
      - name: Create test_config.yml
        run: |
          echo "owner: ${{ secrets.AWS_TAG_OWNER }}" > test_config.yml
      - name: Run tests and build with Maven
        run: mvn --batch-mode --update-snapshots clean verify -DtrimStackTrace=false -PregressionTests -Dtest.coverage=false
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-central-1"
      - name: Publish Test Report for ${{ matrix.docker_db_version }}
        uses: scacap/action-surefire-report@v1
        if: ${{ always() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Destroy cluster
        run: terraform -chdir=cloudSetup/ destroy -auto-approve
        if: always() # also run if tests failed
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Upload regression test result
        uses: actions/upload-artifact@v2
        with:
          name: performance-test-results
          path: target/performanceLog-*.csv
      - name: Upload results to Exasol Demo DB
        run: |
          curl https://www.exasol.com/support/secure/attachment/167973/EXASOL_JDBC-7.1.2.tar.gz -o jdbc.tar.gz
          echo "3e77613fd28daab94257de9cea9fd072fe48d18aef2d5307a4d826ddd3bd49dbd780ba04d78a2513b9c181c1c3f621800f433da32fd7e3c6f7ad622385aed243  jdbc.tar.gz" | sha512sum -c
          tar -xvzf jdbc.tar.gz
          cp target/performanceLog-*.csv target/performanceLog.csv
          # add release name column ($ matches end of line)
          sed "s/\$/,\"$RELEASE_NAME\"/" target/performanceLog.csv > target/performanceLogWithReleaseName.csv
          EXASOL_JDBC-7.1.2/exajload -c demodb.exasol.com -u ${{ secrets.DEMODB_LOG_SUBMIT_USER }} -P ${{ secrets.DEMODB_LOG_SUBMIT_PASS }} -sql "IMPORT INTO EXASOL_JABR.REGRESSION_TEST_RESULTS  FROM LOCAL CSV FILE './target/performanceLogWithReleaseName.csv' COLUMN SEPARATOR = ',' SKIP = 1;"
        env:
          RELEASE_NAME: "${{ github.event.release.tag_name }}"
