name: Regression Tests

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print tag name
        run: echo ${{ github.event.release.tag_name }}
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 11
          cache: "maven"
      - name: Run local smoketests
        run: |
          mvn --batch-mode --update-snapshots clean artifact-reference-checker:verify test -DtrimStackTrace=false -Dtest.coverage=false \
            -Derror-code-crawler.skip=true -Dmaven.javadoc.skip=true -Dproject-keeper.skip=true
      - name: Create AWS test setup
        run: |
          echo "owner = \"$OWNER\"" > cloudSetup/terraform.tfvars
          echo "deputy = \"$DEPUTY\"" >> cloudSetup/terraform.tfvars
          terraform -chdir=cloudSetup/ init
          terraform -chdir=cloudSetup/ apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          OWNER: ${{ secrets.AWS_TAG_OWNER }}
          DEPUTY: ${{ secrets.AWS_TAG_DEPUTY }}
      - name: Create test_config.properties
        run: |
          echo "owner = ${{ secrets.AWS_TAG_OWNER }}" > test_config.properties
          echo "s3CacheBucket = persistent-s3-vs-test-file-cache" >> test_config.properties
      - name: Run regression tests
        run: |
          mvn --batch-mode verify \
               -DtrimStackTrace=false -PregressionTests -Dtest.coverage=false \
               -Derror-code-crawler.skip=true -Dmaven.javadoc.skip=true -Dproject-keeper.skip=true
      - name: Publish Test Report
        uses: scacap/action-surefire-report@v1
        if: ${{ always() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload regression test result
        uses: actions/upload-artifact@v3
        with:
          name: performance-test-results
          path: target/performanceLog-*.csv
      - name: Upload results to Exasol Demo DB
        run: ./.ci/upload_regression_test_result.sh
        env:
          RELEASE_NAME: "${{ github.event.release.tag_name }}"
          REGRESSION_TEST_RESULT_SUBMIT_USER: "${{ secrets.REGRESSION_TEST_RESULT_SUBMIT_USER }}"
          REGRESSION_TEST_RESULT_SUBMIT_PASSWORD: "${{ secrets.REGRESSION_TEST_RESULT_SUBMIT_PASSWORD }}"
      - name: Destroy cluster
        run: terraform -chdir=cloudSetup/ destroy -auto-approve
        if: always() # also run if tests failed
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Report Status to Slack channel
        if: always()
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notification_title: "AWS S3 VS Performance regression tests: {workflow} has {status_message}"
          message_format: "{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.INTEGRATION_TEAM_SLACK_NOTIFICATION_WEBHOOK }}
